function hhlp(code,help) {
    this.code=code;
    this.help=help;
}

hdrhlp=[
 new hhlp('+ANG-RSL','+ Unsymmetric Angular Resolution')
,new hhlp('+DATA-ERR','+ Unsymmetric Data Error, see `ERR-ANALYS`')
,new hhlp('+DATA-ERR1','+ Unsymmetric data uncertainty')
,new hhlp('+DATA-ERR2','+ Unsymmetric 2nd data uncertainty')
,new hhlp('+E-ERR','+ Unsymmetric Outgoing Particle Energy Error')
,new hhlp('+E-LVL-ERR','+ Unsymmetric Level Energy Error')
,new hhlp('+EN-ERR','+ Unsymmetric Energy Error')
,new hhlp('+EN-RES-ER','+ Unsymmetric Resonance Energy Error')
,new hhlp('+EN-RSL','+ Unsymmetric Energy Resolution')
,new hhlp('+ERR-5','+ Unsymmetric 5th Systematic Error, see `ERR-ANALYS`.')
,new hhlp('+ERR-S','+ Unsymmetric Statistical Error')
,new hhlp('+ERR-SYS','+ Unsymmetric Systematic Error')
,new hhlp('+ERR-T','+ Unsymmetric Total Error')
,new hhlp('+MISC-ERR','+ Unsymemtric Error in Miscellaneous Value')
,new hhlp('+MONIT-ERR','+ Unsymmetric Error in Value Assumed for Normalization')
,new hhlp('+RATIO-ERR','+ Unsymmetric Ratio Error, see `ERR-ANALYS`.')
,new hhlp('+SUM-ERR','+ Unsymmetric Error in Sum, see `ERR-ANALYS`.')
,new hhlp('ANAL-STEP','Analysis Energy Step')
,new hhlp('ANG','Angle, Laboratory System')
,new hhlp('ANG1','1st Angle, definition given in BIB Section')
,new hhlp('ANG1-CM','Angle, C.M. System, definition given in BIB')
,new hhlp('ANG1-CM-MN','Lower Limit of First Angle, C.M. System')
,new hhlp('ANG1-CM-MX','Upper Limit of First Angle, C.M. System')
,new hhlp('ANG1-ERR','1st Angle Error, definition given in BIB Section')
,new hhlp('ANG2','2nd Angle, definition given in BIB Section')
,new hhlp('ANG2-CM','Angle, C.M. System, definition given in BIB')
,new hhlp('ANG2-ERR','2nd Angle Error, definition given in BIB Section')
,new hhlp('ANG2-RL-CM','Relative 2nd Angle, C.M. System')
,new hhlp('ANG3','3rd Angle, definition given in BIB Section')
,new hhlp('ANG4','4th Angle, definition given in BIB Section')
,new hhlp('ANG-AZ','Azimuthal Angle')
,new hhlp('ANG-AZ1','Azimuthal Angle')
,new hhlp('ANG-AZ2','Azimuthal Angle')
,new hhlp('ANG-AZ-RL','Azimuthal Angle Between 2 Reaction Planes')
,new hhlp('ANG-CM','Angle, C.M. System')
,new hhlp('ANG-CM-DN','Angle for Reaction Ratio Denominator, C.M. System')
,new hhlp('ANG-CM-MAX','Upper Limit of Angular Range, C.M. System')
,new hhlp('ANG-CM-MIN','Lower Limit of Angular Range, C.M. System')
,new hhlp('ANG-CM-NM','Angle for Reaction Ratio Numerator, C.M. System')
,new hhlp('ANG-DN','Angle, Reaction Ratio Denominator')
,new hhlp('ANG-ERR','Angle Error')
,new hhlp('ANG-ERR-D','Digitizing error of angle')
,new hhlp('ANG-MAX','Upper Limit of Angular Range, Lab. System')
,new hhlp('ANG-MIN','Lower Limit of Angular Range, Lab. System')
,new hhlp('ANG-MN','Mean angle of correlated pair')
,new hhlp('ANG-MN-ERR','Error of Mean angle of correlated pair')
,new hhlp('ANG-NM','Angle, Reaction Ratio Numerator')
,new hhlp('ANG-NRM','Angle at which normalization was made')
,new hhlp('ANG-RL','Relative Angle')
,new hhlp('ANG-RL-CM','Relative Angle, C.M. System')
,new hhlp('-ANG-RSL','- Unsymmetric Angular Resolution')
,new hhlp('ANG-RSL','Angular Resolution')
,new hhlp('ASSUM','Assumed Value, defined under `ASSUMED`.')
,new hhlp('ASSUM1','1st Assumed Value, defined under `ASSUMED`.')
,new hhlp('ASSUM1-ERR','1st Assumed Value Error')
,new hhlp('ASSUM1-MAX','Upper Limit of 1st Assumed Value')
,new hhlp('ASSUM1-MIN','Lower Limit of 1st Assumed Value')
,new hhlp('ASSUM2','2nd Assumed Value, defined under `ASSUMED`.')
,new hhlp('ASSUM2-ERR','2nd Assumed Value Error')
,new hhlp('ASSUM2-MAX','Upper Limit of 2nd Assumed Value')
,new hhlp('ASSUM2-MIN','Lower Limit of 2nd Assumed Value')
,new hhlp('ASSUM3','3rd Assumed Value, defined under `ASSUMED`.')
,new hhlp('ASSUM3-ERR','3th Assumed Value Error')
,new hhlp('ASSUM4','4th Assumed Value, defined under `ASSUMED`.')
,new hhlp('ASSUM4-ERR','4th Assumed Value Error')
,new hhlp('ASSUM5','5th Assumed Value, defined under `ASSUMED`.')
,new hhlp('ASSUM5-ERR','5th Assumed Value Error')
,new hhlp('ASSUM-ERR','Error in Assumed Value')
,new hhlp('ASSUM-MAX','Upper Limit of Assumed Value')
,new hhlp('ASSUM-MIN','Lower Limit of Assumed Value')
,new hhlp('CNTY','Centrality')
,new hhlp('CNTY-ERR','Centrality error')
,new hhlp('CNTY-MAX','Upper limit of Centrality')
,new hhlp('CNTY-MIN','Lower limit of Centrality')
,new hhlp('COS','Cosine of Angle, Laboratory System')
,new hhlp('COS-CM','Cosine of Angle, C.M.System')
,new hhlp('COS-CM-MAX','Upper Limit of Cosine Range, C.M. System')
,new hhlp('COS-CM-MIN','Lower Limit of Cosine Range, C.M. System')
,new hhlp('COS-ERR','Cosine Error')
,new hhlp('COS-ERR-D','Digitizing Error of Cosine')
,new hhlp('COS-MAX','Upper Limit of Cosine Range, Lab. System')
,new hhlp('COS-MIN','Lower Limit of Cosine Range, Lab. System')
,new hhlp('COS-RSL','Cosine Angular Resolution')
,new hhlp('DATA','Value of Quantity Specified under `REACTION`')
,new hhlp('DATA-APRX','Approximate Value of Quantity specif. under `REACTION`')
,new hhlp('DATA-CM','Value of Quantity specif. under `REACTION`, C.M. Sys.')
,new hhlp('-DATA-ERR','- Unsymmetric Data Error, see `ERR-ANALYS`.')
,new hhlp('DATA-ERR','Error in Value of Quantity, defined under `ERR-ANALYS`')
,new hhlp('-DATA-ERR1','- Unsymmetric data uncertainty')
,new hhlp('DATA-ERR1','1st Data Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('-DATA-ERR2','- Unsymmetric 2nd data uncertainty')
,new hhlp('DATA-ERR2','2nd Data Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('DATA-ERR3','3rd Data Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('DATA-ERR4','4th Data Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('DATA-ERR5','5th Data Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('DATA-ERR6','6th Data Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('DATA-MAX','Upper Limit of Quantity specified under `REACTION`')
,new hhlp('DATA-MIN','Lower Limit of Quantity specified under `REACTION`')
,new hhlp('DATA-MN-CM','Lower Lim.of Quant.specif.under `REACTION`, C.M.Sys.')
,new hhlp('DATA-MX-CM','Upper Lim.of Quant.specif.under `REACTION`, C.M.Sys.')
,new hhlp('DCNST','Decay constant')
,new hhlp('DCNST-ERR','Error in decay constant')
,new hhlp('DECAY-FLAG','Decay Flag. See corresponding Flag in BIB section')
,new hhlp('E','Energy of Outgoing Particle, Lab. System')
,new hhlp('E1','1st Outgoing Part. En., defined under `EN-SEC`')
,new hhlp('E1-CM','1st Outgoing Part. En., C.M. defined under `EN-SEC`')
,new hhlp('E1-MAX','Upper Limit, 1st Outgoing Part. En.Range, see `EN-SEC`')
,new hhlp('E1-MIN','Lower Limit, 1st Outgoing Part. En.Range, see `EN-SEC`')
,new hhlp('E2','2nd Outgoing Part. Energy, defined under `EN-SEC`')
,new hhlp('E2-MAX','Upper Limit, 2nd Outgoing Part. En.Range, see `EN-SEC`')
,new hhlp('E2-MIN','Lower Limit, 2nd Outgoing Part. En.Range, see `EN-SEC`')
,new hhlp('E3','3rd Outgoing Particle Energy, defined under `EN-SEC`')
,new hhlp('E3-MIN','Lower Limit, 3rd Outgoing Part. En.Range, see `EN-SEC`')
,new hhlp('E4','4th Outgoing Particle Energy, defined under `EN-SEC`')
,new hhlp('E5','5th Outgoing Particle Energy, defined under `EN-SEC`')
,new hhlp('E-APRX','Approx. Energy of Outgoing Particle, Lab. System')
,new hhlp('E-CM','Energy of Outgoing Particle, C.M. System')
,new hhlp('E-CM-MAX','Upper Limit of Outgoing Part. En. Range, C.M. Sys.')
,new hhlp('E-CM-MIN','Lower Limit of Outgoing Part. En. Range, C.M. Sys.')
,new hhlp('E-DGD','Degradation in Incident vs. Outgoing Particle Energy')
,new hhlp('E-DGD-ERR','Error in Degradation in Incident vs. Outgoing Part.En.')
,new hhlp('E-DGD-MAX','Upper Limit of Degradat. in Inc. vs. Outgoing Part.En.')
,new hhlp('E-DGD-MIN','Lower Limit of Degradat. in Inc. vs. Outgoing Part.En.')
,new hhlp('E-DN','Outgoing Particle Enery, Reaction Ratio Denominator')
,new hhlp('-E-ERR','- Unsymmetric Outgoing Particle Energy Error')
,new hhlp('E-ERR','Outgoing Particle Energy Error')
,new hhlp('E-ERR-DIG','Digitizing error of outgoing particle energy')
,new hhlp('E-EXC','Excitation Energy')
,new hhlp('E-EXC1','1st Excitation Energy, defined under EN-SEC`')
,new hhlp('E-EXC1-MAX','Upper Limit of 1st Excitation Energy Range')
,new hhlp('E-EXC1-MIN','Lower Limit of 1st Excitation Energy Range')
,new hhlp('E-EXC2','2nd Excitation Energy, defined under EN-SEC`.')
,new hhlp('E-EXC3','3rd Excitation Energy, defined under EN-SEC`.')
,new hhlp('E-EXC-DN','Excitation Energy for denominator of reaction ratio')
,new hhlp('E-EXC-ERR','Excitation Energy Error')
,new hhlp('E-EXC-MAX','Upper Limit of Excitation Energy Range')
,new hhlp('E-EXC-MEAN','Mean Excitation Energy')
,new hhlp('E-EXC-MIN','Lower Limit of Excitation Energy Range')
,new hhlp('E-EXC-NM','Excitation Energy for numerator of reaction ratio')
,new hhlp('E-GAIN','Gain in Incident vs. Outgoing Particle Energy')
,new hhlp('E-GAIN-ERR','Error in Gain in Incident vs. Outgoing Particle Energy')
,new hhlp('E-K','Kinetic energy, Lab.system')
,new hhlp('ELEM1','Atomic Number of 1st Element')
,new hhlp('ELEM2','Atomic Number of 2nd Element')
,new hhlp('ELEM3','Atomic Number of 3rd Element')
,new hhlp('ELEM-DN','Atomic Number, Reaction Ratio Denominator')
,new hhlp('ELEMENT','Atomic Number of Element')
,new hhlp('ELEM-MAX','Upper Limit of Atomic Number Range')
,new hhlp('ELEM-MIN','Lower Limit of Atomic Number Range')
,new hhlp('ELEM-NM','Atomic Number, Reaction Ratio Numerator')
,new hhlp('ELEM-NRM','Atomic Number of Nuclide Used for Normalization')
,new hhlp('E-LVL','Level Energy')
,new hhlp('E-LVL1','1st Level Energy, defined under `EN-SEC`')
,new hhlp('E-LVL2','2nd Level Energy, defined under `EN-SEC`')
,new hhlp('E-LVL-DN','Level Energy, Reaction Ratio Denominator')
,new hhlp('-E-LVL-ERR','- Unsymmetric Level Energy Error')
,new hhlp('E-LVL-ERR','Level Energy Error')
,new hhlp('E-LVL-FIN','Final Level of Gamma Transition')
,new hhlp('E-LVL-FIN1','Final Level of Gamma Transition, def.under EN-SEC')
,new hhlp('E-LVL-FIN2','Final Level of Gamma Transition, def.under EN-SEC')
,new hhlp('E-LVL-INI','Initial Level of Gamma Transition')
,new hhlp('E-LVL-INI1','Initial Level of Gamma Transition, def.under EN-SEC')
,new hhlp('E-LVL-INI2','Initial Level of Gamma Transition, def.under EN-SEC')
,new hhlp('E-LVL-MAX','Upper Energy Limit of Discrete Level Group')
,new hhlp('E-LVL-MEAN','Mean Level Energy')
,new hhlp('E-LVL-MIN','Lower Energy Limit of Discrete Level Group')
,new hhlp('E-LVL-NM','Level Energy, Reaction Ratio Numerator')
,new hhlp('E-LVL-NRM','Level Energy Used for Normalization')
,new hhlp('E-MAX','Upper Limit of Outgoing Particle En. Range, Lab. Sys.')
,new hhlp('E-MAX-CM','Upper Limit of Outgoing Particle En. Range, C.M. Sys.')
,new hhlp('E-MAX-DN','Outgoing Particle Energy, Reaction Ratio Denominator')
,new hhlp('E-MAX-NM','Outgoing Particle Energy, Reaction Ratio Numerator')
,new hhlp('E-MEAN','Mean Energy of Outgoing Particles, Lab. System')
,new hhlp('E-MIN','Lower Limit of Outgoing Particle En. Range, Lab. Sys.')
,new hhlp('E-MIN-CM','Lower Limit of Outgoing Particle En. Range, C.M. Sys.')
,new hhlp('E-MIN-DN','Outgoing Particle Enery, Reaction Ratio Denominator')
,new hhlp('E-MIN-NM','Outgoing Particle Enery, Reaction Ratio Numerator')
,new hhlp('EMS','Effective Mass Squared')
,new hhlp('EMS1','1st Effective Mass Squared, defined under `MOM-SEC`.')
,new hhlp('EMS1-MAX','Upper Limit, 1st Effective Mass Squared, see `MOM-SEC`')
,new hhlp('EMS1-MIN','Lower Limit, 1st Effective Mass Squared, see `MOM-SEC`')
,new hhlp('EMS2','2nd Effective Mass Squared, defined under `MOM-SEC`.')
,new hhlp('EMS2-MAX','Upper Limit, 2nd Effective Mass Squared, see `MOM-SEC`')
,new hhlp('EMS2-MIN','Lower Limit, 2nd Effective Mass Squared, see `MOM-SEC`')
,new hhlp('EMS3','3rd Effective Mass Squared, defined under `MOM-SEC`')
,new hhlp('EMS4','4th Effective Mass Squared, defined under `MOM-SEC`')
,new hhlp('EMS5','5th Effective Mass Squared, defined under `MOM-SEC`')
,new hhlp('EN','Energy of Incident Projectile, Laboratory System')
,new hhlp('EN-APRX','Approximate Value of Incident Projectile Energy')
,new hhlp('EN-CM','Incident Projectile Energy relative to target')
,new hhlp('EN-CM-MAX','Upper Limit of C.M. Incident Projectile Energy Range')
,new hhlp('EN-CM-MIN','Lower Limit of C.M. Incident Projectile Energy Range')
,new hhlp('EN-CM-NRM','Inc.Proj. Energy (in c.m.) Used for Normalization')
,new hhlp('EN-DN','Incident Energy for Reaction Ratio Denominator')
,new hhlp('EN-DUM-DN','Dummy Incident Energy, Reaction Ratio Denominator')
,new hhlp('EN-DUMMY','Dummy Incident Proj. Energy, for broad spectrum')
,new hhlp('EN-DUM-NM','Dummy Incident Energy, Reaction Ratio Numerator')
,new hhlp('-EN-ERR','- Unsymmetric Energy Error')
,new hhlp('EN-ERR','Uncertainty in Incident Projectile Energy')
,new hhlp('EN-ERR1','1st Incident Projectile Energy Error, see `ERR-ANALYS`')
,new hhlp('EN-ERR2','2nd Incident Projectile Energy Error, see `ERR-ANALYS`')
,new hhlp('EN-ERR3','3rd Incident Projectile Energy Error, see `ERR-ANALYS`')
,new hhlp('EN-ERR-DIG','Digitizing error of incident particle energy')
,new hhlp('E-NM','Outgoing Particle Energy, Reaction Ratio Numerator')
,new hhlp('EN-MAX','Upper Limit of Incident Projectile Energy Range')
,new hhlp('EN-MEAN','Mean Energy of Incident Projectile Spectrum')
,new hhlp('EN-MEAN-DN','Inc. Spectr. Mean Energy, Reaction Ratio Denominator')
,new hhlp('EN-MEAN-NM','Inc. Spectr. Mean Energy, Reaction Ratio Numerator')
,new hhlp('E-NM-ERR','Error in Outgoing Particle En., Reaction Ratio Numerator')
,new hhlp('EN-MIN','Lower Limit of Incident Projectile Energy Range')
,new hhlp('EN-MIN-APX','Approximate Lower Limit Incident Projectile Energy')
,new hhlp('EN-MIN-DN','Lower Limit of Inc. En. Range, Reaction Ratio Denom.')
,new hhlp('EN-MIN-NM','Lower Limit of Inc. En. Range, Reaction Ratio Numer.')
,new hhlp('EN-NM','Incident Projectile Energy, Reaction Ratio Numerator')
,new hhlp('EN-NRM','Incident Projectile Energy Used for Normalization')
,new hhlp('EN-NRM1','1st Incident Proj.En. for Normalization, see `MONITOR`')
,new hhlp('EN-NRM2','2nd Incident Proj.En. for Normalization, see `MONITOR`')
,new hhlp('EN-NRM3','3rd Incident Proj.En. for Normalization, see `MONITOR`')
,new hhlp('EN-NRM-MAX','Upper Limit of Incident En. Range for Normalization')
,new hhlp('EN-NRM-MIN','Lower Limit of Incident En. Range for Normalization')
,new hhlp('EN-NRM-RSL','Energy Resolution of Normalization Incident Energy')
,new hhlp('EN-RES','Resonance Energy')
,new hhlp('EN-RES-CM','Resonance Energy, C.M. System')
,new hhlp('-EN-RES-ER','- Unsymmetric Resonance Energy Error')
,new hhlp('EN-RES-ERR','Error in Resonance Energy')
,new hhlp('EN-RES-MAX','Upper Limit of Resonance Energy')
,new hhlp('EN-RES-MIN','Lower Limit of Resonance Energy')
,new hhlp('E-NRM','Energy of Outgoing Particle Used for Normalization')
,new hhlp('E-NRM1','Energy of First Outgoing Particle Used for Normalization')
,new hhlp('E-NRM2','Energy of Second Outgoing Particle Used for Normalization')
,new hhlp('-EN-RSL','- Unsymmetric Energy Resolution')
,new hhlp('EN-RSL','Incident Projectile Energy Resolution (Unspecified)')
,new hhlp('EN-RSL-DN','Inc.Proj.Energy Resol.(FWHM), Reaction Ratio Denominator')
,new hhlp('EN-RSL-FW','Incident Projectile Energy Resolution (FWHM)')
,new hhlp('EN-RSL-HW','Incident Projectile Energy Resolution (+-1/2 FWHM)')
,new hhlp('EN-RSL-NM','Inc.Proj.Energy Resol.(FWHM), Reaction Ratio Numerator')
,new hhlp('E-RL','Relative Energy of Outgoing Particle, Lab. System')
,new hhlp('E-RL-CM','Relative Energy of Outgoing Particle, C.M. System')
,new hhlp('ERR-1','1st Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-10','10th Systematic Uncert., defined under `ERR-ANALYS`')
,new hhlp('ERR-11','11th Systematic Uncert., defined under `ERR-ANALYS`')
,new hhlp('ERR-12','12th Systematic Uncert., defined under `ERR-ANALYS`')
,new hhlp('ERR-13','13th Systematic Uncert., defined under `ERR-ANALYS`')
,new hhlp('ERR-14','14th Systematic Uncert., defined under `ERR-ANALYS`')
,new hhlp('ERR-15','15th Systematic Uncert., defined under `ERR-ANALYS`')
,new hhlp('ERR-2','2nd Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-3','3rd Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-4','4th Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('-ERR-5','- Unsymmetric 5th Systematic Error, see `ERR-ANALYS`.')
,new hhlp('ERR-5','5th Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-6','6th Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-7','7th Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-8','8th Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-9','9th Systematic Uncertainty, defined under `ERR-ANALYS`')
,new hhlp('ERR-DIG','Digitizing error (of DATA)')
,new hhlp('ERR-EDD','Error of energy value given under DECAY-DATA')
,new hhlp('ERR-HL','Error of half-life value givein under DECAY-DATA')
,new hhlp('ERR-IDD','Error of intensity value given under DECAY-DATA')
,new hhlp('-ERR-S','- Unsymmetric Statistical Uncertainty')
,new hhlp('ERR-S','Statistical Uncertainty (1-Sigma)')
,new hhlp('-ERR-SYS','- Unsymmetric Systematic Error')
,new hhlp('ERR-SYS','Total Systematic Uncertainty')
,new hhlp('-ERR-T','- Unsymmetric Total Uncertainty')
,new hhlp('ERR-T','Total Uncertainty (1-Sigma)')
,new hhlp('E-RSL','Otugoing Projectile Energy Resolution')
,new hhlp('E-RSL-FW','Secondary energy resolution (full width at half maximum)')
,new hhlp('E-TPB','Transverse kinetic energy, lab. sys., in Pb glass detector')
,new hhlp('E-TPB-MAX','Upper limit, transv.kin.energy, lab.sys., in Pb glass det.')
,new hhlp('E-TPB-MIN','Lower limit, transv.kin.energy, lab.sys., in Pb glass det.')
,new hhlp('E-TR','Transverse kinetic energy, laboratory system')
,new hhlp('E-TR-CM','Transverse kinetic energy, center-of-mass system')
,new hhlp('E-TR-MAX','Upper limit of transverse kinetic energy, lab.system')
,new hhlp('E-TR-MIN','Lower limit of transverse kinetic energy, lab.system')
,new hhlp('E-ZCAL','Transverse kin. energy, Lab.sys., in zero-degr.calorimeter')
,new hhlp('FLAG','Flag, defined under `FLAG`.')
,new hhlp('GRP-NUM','Group number (of delayed neutrons)')
,new hhlp('HL','Half-Life of Nuclide Specified.')
,new hhlp('HL1','Half-Life of 1st Nucleus Specified')
,new hhlp('HL1-ERR','Error in Half-Life of 1st Nucleus Specified')
,new hhlp('HL2','Half-Life of 2nd Nucleus Specified')
,new hhlp('HL2-ERR','Error in Half-Life of 2nd Nucleus Specified')
,new hhlp('HL3','Half-Life of 3rd Nucleus Specified')
,new hhlp('HL3-ERR','Error in Half-Life of 3rd Nucleus Specified')
,new hhlp('HL4','Half-Life of 4th Nucleus Specified')
,new hhlp('HL4-ERR','Error in Half-Life of 4th Nucleus Specified')
,new hhlp('HL-DN','Half-Life of nuclide specified in ratio denominator')
,new hhlp('HL-ERR','Error in Half-Life')
,new hhlp('HL-NM','Half-Life of nuclide specified in ratio numerator')
,new hhlp('HL-NRM','Half-Life of nuclide to which data is normalized')
,new hhlp('IAS-NUMB','Level Number of Isobaric Analog State')
,new hhlp('ISOMER','Isomer for Nuclide Given')
,new hhlp('ISOMER1','1st Isomer for Nuclide')
,new hhlp('ISOMER2','2nd Isomer for Nuclide')
,new hhlp('ISOMER-DN','Isomer for Nuclide, REACTION Ratio Denominator')
,new hhlp('ISOMER-NM','Isomer for Nuclide, REACTION Ratio Numerator')
,new hhlp('ISO-NUMB','Level Number of Isobaric Analog State')
,new hhlp('KQ','Indices for tensor analyzing power')
,new hhlp('KT','Spectrum Temperature (energy units)')
,new hhlp('KT-DN','Spectrum Temperature, Reaction Ratio Denominator')
,new hhlp('KT-ERR','Error in Spectrum Temperature')
,new hhlp('KT-K','Spectrum Temperature (temperature units)')
,new hhlp('KT-NM','Spectrum Temperature, Reaction Ratio Numerator')
,new hhlp('KT-NRM','Temperature of reference Maxwellian spectrum')
,new hhlp('LVL','Level Energy as additional information')
,new hhlp('LVL-FIN','Final Level Energy as additional information')
,new hhlp('LVL-FIN1','1st Final Level Energy as additional information')
,new hhlp('LVL-FIN2','2nd Final Level Energy as additional information')
,new hhlp('LVL-FLAG','Level Flag, Link to information under `LEVEL-PROP`')
,new hhlp('LVL-INI','Initial Level Energy as additional information')
,new hhlp('LVL-INI1','1st Initial Level Energy as additional information')
,new hhlp('LVL-INI2','2nd Initial Level Energy as additional information')
,new hhlp('LVL-NUMB','Level Number')
,new hhlp('LVL-NUM-DN','Level Number, Reaction Ratio Denominator')
,new hhlp('LVL-NUM-NM','Level Number, Reaction Ratio Numerator')
,new hhlp('M1','Linear Momentum of 1st Outgoing Particle')
,new hhlp('M1-MAX','Upper Limit of 1st Outgoing Particle Linear Momentum')
,new hhlp('M1-MIN','Lower Limit of 1st Outgoing Particle Linear Momentum')
,new hhlp('M1-SEC-MAX','Upper Limit of 1st Outgoing Particle Linear Momentum')
,new hhlp('M1-SEC-MIN','Lower Limit of 1st Outgoing Particle Linear Momentum')
,new hhlp('M2','Linear Momentum of 2nd Outgoing Particle')
,new hhlp('M2-MAX','Upper Limit of 2nd Outgoing Particle Linear Momentum')
,new hhlp('M2-MIN','Lower Limit of 2nd Outgoing Particle Linear Momentum')
,new hhlp('M2-SEC-MAX','Upper Limit of 2nd Outgoing Particle Linear Momentum')
,new hhlp('M2-SEC-MIN','Lower Limit of 2nd Outgoing Particle Linear Momentum')
,new hhlp('M3','Linear Momentum of 3rd Outgoing Particle')
,new hhlp('M4','Linear Momentum of 4th Outgoing Particle')
,new hhlp('M5','Linear Momentum of 5th Outgoing Particle')
,new hhlp('MASS','Atomic Mass of Nuclide')
,new hhlp('MASS1','Atomic Mass of 1st Nuclide')
,new hhlp('MASS1-MAX','Maximum Atomic Mass of 1st Nuclide')
,new hhlp('MASS2','Atomic Mass of 2nd Nuclide')
,new hhlp('MASS2-MIN','Minimum Atomic Mass of 2nd Nuclide')
,new hhlp('MASS3','Atomic Mass of 3rd Nuclide')
,new hhlp('MASS-DN','Atomic Mass of Nuclide, Reaction Ratio Denominator')
,new hhlp('MASS-MAX','Upper Limit of Atomic Mass Range')
,new hhlp('MASS-MIN','Lower Limit of Atomic Mass Range')
,new hhlp('MASS-NM','Atomic Mass of Nuclide, Reaction Ratio Numerator')
,new hhlp('MASS-NRM','Atomic Mass of Nuclide used for Normalization')
,new hhlp('MASS-RATIO','Ratio of Atomic Masses of Fission Fragments')
,new hhlp('MASS-RSL','Mass Resolution')
,new hhlp('MISC','Miscellaneous Information, defined under `MISC-COL`.')
,new hhlp('MISC1','1st Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC10','10th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC1-ERR','Error in 1st Miscellaneous Field')
,new hhlp('MISC2','2nd Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC2-ERR','Error in 2nd Miscellaneous Field')
,new hhlp('MISC3','3rd Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC3-ERR','Error in 3rd Miscellaneous Field')
,new hhlp('MISC4','4th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC4-ERR','Error in 4th Miscellaneous Field')
,new hhlp('MISC5','5th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC5-ERR','Error in 5th Miscellaneous Field')
,new hhlp('MISC6','6th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC6-ERR','Error in 6th Miscellaneous Field')
,new hhlp('MISC7','7th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC7-ERR','Error in 7th Miscellaneous Field')
,new hhlp('MISC8','8th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('MISC8-ERR','Error in 8th Miscellaneous Field')
,new hhlp('MISC9','9th Miscellaneous Field, defined under `MISC-COL`')
,new hhlp('-MISC-ERR','- Unsymemtric Error in Miscellaneous Value')
,new hhlp('MISC-ERR','Error in Miscellaneous Value')
,new hhlp('MISC-ERR-D','Digitizng Error in Miscellaneous Value')
,new hhlp('MOM','Linear Momentum of Incident Projectile')
,new hhlp('MOMENTUM L','Angular Momentum (L) of Resonance')
,new hhlp('MOM-ERR','Error of Linear Momentum of Incident Projectile')
,new hhlp('MOM-MAX','Maximum Linear Momentum of Incident Projectile')
,new hhlp('MOM-MIN','Minimum Linear Momentum of Incident Projectile')
,new hhlp('MOM-RSL','Incident Projectile Linear Momentum Resolution')
,new hhlp('MOM-SEC','Linear Momentum of Outgoing Particle')
,new hhlp('MOM-SEC1','1st Linear Momentum of Outgoing Particle')
,new hhlp('MOM-SEC2','2nd Linear Momentum of Outgoing Particle')
,new hhlp('MOM-SEC3','3rd Linear Momentum of Outgoing Particle')
,new hhlp('MOM-SEC4','4th Linear Momentum of Outgoing Particle')
,new hhlp('MOM-SEC5','5th Linear Momentum of Outgoing Particle')
,new hhlp('MOM-SEC-MN','Minimum Linear Momentum of Outgoing Particle')
,new hhlp('MOM-TR','Momentum transfer (in units MeV/c or equiv.)')
,new hhlp('MOM-TR-ERR','Error of momentum transfer')
,new hhlp('MONIT','Normalization Value for Reaction given under `MONITOR`')
,new hhlp('MONIT1','1st Normalization Value, see `MONITOR`')
,new hhlp('MONIT1-ERR','Error in 1st Normalization Value')
,new hhlp('MONIT2','2nd Normalization Value, see `MONITOR`')
,new hhlp('MONIT2-ERR','Error in 2nd Normalization Value')
,new hhlp('MONIT3','3rd Normalization Value, see `MONITOR`')
,new hhlp('MONIT3-ERR','Error in 3rd Normalization Value')
,new hhlp('MONIT4','4th Normalization Value, see `MONITOR`')
,new hhlp('MONIT4-ERR','Error in 4th Normalization Value')
,new hhlp('MONIT5','5th Normalization Value, see `MONITOR`')
,new hhlp('MONIT5-ERR','Error in 5th Normalization Value')
,new hhlp('MONIT6','6th Normalization Value, see `MONITOR`')
,new hhlp('MONIT6-ERR','Error in 6th Normalization Value')
,new hhlp('MONIT7','7th Normalization Value, see `MONITOR`')
,new hhlp('MONIT8','8th Normalization Value, see `MONITOR`')
,new hhlp('MONIT-CM','Normalization Value, C.M. System, see `MONITOR`')
,new hhlp('MONIT-DN','Normalization Value for denominator of reaction ratio')
,new hhlp('-MONIT-ERR','- Unsymmetric Error in Value Assumed for Normalization')
,new hhlp('MONIT-ERR','Error in Normalization Value')
,new hhlp('MONIT-NM','Normalization value for numerator of ratio')
,new hhlp('MSS-T','Transverse mass of outgoing proj.')
,new hhlp('MSS-TK','Transverse - rest mass of outgoing proj.')
,new hhlp('MSS-TK-MAX','Maximum value of outgoing proj.transverse - rest mass')
,new hhlp('MSS-TK-MIN','Minimum value of outgoing proj.transverse - rest mass')
,new hhlp('MU-ADLER','Mu')
,new hhlp('N-OUT','Number of Emitted Neutrons')
,new hhlp('NUMBER','Fitting Coefficient Number')
,new hhlp('NUMBER-CM','Fitting Coefficient Number, for Data in C.M. System')
,new hhlp('PARITY','Parity of Resonance')
,new hhlp('PART-OUT','Number of Emitted Particles')
,new hhlp('POLAR','Polarity')
,new hhlp('POLAR-DN','Polarity for denominator of reaction ratio')
,new hhlp('POLAR-NM','Polarity for numerator of reaction ratio')
,new hhlp('POL-BM','Beam Polarization')
,new hhlp('POL-BM-ERR','Beam Polarization Error')
,new hhlp('POL-BM-MAX','Upper Limit of Beam Polarization')
,new hhlp('POL-BM-MIN','Lower Limit of Beam Polarization')
,new hhlp('POL-TR','Target Polarization')
,new hhlp('POL-TR-ERR','Target Polarization Error')
,new hhlp('P-OUT','Number of Emitted Protons')
,new hhlp('PRJ','Number of participating projectiles')
,new hhlp('PRJ-AV','Average number of participating projectiles')
,new hhlp('q','Momentum transfer, q')
,new hhlp('q-CM','Momentum transfer, q, center of mass system')
,new hhlp('Q-VAL','Q-Value')
,new hhlp('Q-VAL-APRX','Approximate Q-Value')
,new hhlp('Q-VAL-ERR','Q-Value Uncertainty')
,new hhlp('Q-VAL-MAX','Upper Limit of Q-Value')
,new hhlp('Q-VAL-MIN','Lower Limit of Q-Value')
,new hhlp('Q-VAL-RSL','Q-Value Resolution')
,new hhlp('RAP','Rapidity (fn En+mom(par)/En-mom(par))')
,new hhlp('RAP-AV','Avg.Rapidity (fn En+mom(par)/En-mom(par))')
,new hhlp('RAP-AV-ERR','Avg.Rapidity error')
,new hhlp('RAP-ERR','Rapidity (relativistic data)')
,new hhlp('RAP-MAX','Upper limit of rapidity (relativistic data)')
,new hhlp('RAP-MIN','Lower limit of rapidity (relativistic data)')
,new hhlp('RAP-PS','Pseudo rapidity (fn mon+mom(par)/mon-mom(par)')
,new hhlp('RAP-PS-MAX','Upper limit of pseudo rapidity (fn mon+mom(par)/mon-mom(par)')
,new hhlp('RAP-PS-MIN','Lower limit of pseudo rapidity (fn mon+mom(par)/mon-mom(par)')
,new hhlp('RATIO','Ratio Value of Quantity specified under `REACTION`')
,new hhlp('RATIO-APRX','Approximate Value of Ratio')
,new hhlp('-RATIO-ERR','- Unsymmetric Ratio Error')
,new hhlp('RATIO-ERR','Ratio Error')
,new hhlp('RATIO-ERR1','1st Ratio Error')
,new hhlp('RATIO-ERR2','2nd Ratio Error')
,new hhlp('RATIO-ERR3','3rd Ratio Error')
,new hhlp('RATIO-MAX','Upper Limit of Ratio')
,new hhlp('RATIO-MIN','Lower Limit of Ratio')
,new hhlp('S','Distance along S-curve for range of E1 and E2')
,new hhlp('S-MEAN','Mean distance along S-curve for range of E1 and E2')
,new hhlp('SPIN J','Spin (J)')
,new hhlp('STAND','Numerical Value Assumed')
,new hhlp('STAND1','1st Standard Value, see `STANDARD`')
,new hhlp('STAND1-ERR','Error in 1st Standard Value')
,new hhlp('STAND2','2nd Standard Value, see `STANDARD`.')
,new hhlp('STAND2-ERR','Error in 2nd Standard Value')
,new hhlp('STAND3','3rd Standard Value, see `STANDARD`.')
,new hhlp('STAND3-ERR','Error in 3rd Standard Value')
,new hhlp('STAND-ERR','Standard Error')
,new hhlp('STAT-W G','Statistical-Weight Factor (g)')
,new hhlp('SUM','Sum value of Quantity specified under `REACTION`')
,new hhlp('-SUM-ERR','- Unsymmetric Error in Sum')
,new hhlp('SUM-ERR','Error in Sum')
,new hhlp('-t','4-momentum transfer squared')
,new hhlp('TEMP','Sample Temperature')
,new hhlp('TEMP-ERR','Error in Sample Temperature')
,new hhlp('THICKNESS','Sample Thickness')
,new hhlp('WVE-LN','Wave length of incident particle')
,new hhlp('WVE-NM','Wave Number')
];
